# Generated by Django 5.2.4 on 2025-07-31 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('stu_name', models.CharField(max_length=50)),
                ('roll_no', models.IntegerField(default=1)),
            ],
        ),
    ]
