# Generated by Django 5.2.4 on 2025-07-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cust_name', models.CharField(default='customer', max_length=20)),
                ('mob', models.CharField(max_length=10, unique=True)),
                ('amount', models.CharField(max_length=10)),
            ],
        ),
    ]
